### ISSUE TITLE
nest your docsearch params

### ISSUE THREAD

**Issue by jayhesselberth** [themains/virustotal#2]
You need to nest your docsearch params under template/params and rebuild the site. If you're using the current pkgdown then the JS will be included in the rebuilt pages.

like this:

```yaml
template:
  params:
    bootswatch: cosmo
    docsearch:
      api_key: 59f51aa86ec968850d822427e20517d5
      index_name: virustotal
```
not

```yaml
template:
  params:
    bootswatch: cosmo
  docsearch:
    api_key: 59f51aa86ec968850d822427e20517d5
    index_name: virustotal

```
